<?php
//  Pengulangan
//  for ada 3 bagian, inisialisasi(menentukan variabel awal), kondisi terminasi(memberhentikan pengulangan), 
//intermen/dekremen(supaya bisa maju atau mundur)
// while, konisi terminasi , selama kondisi bernilai true lakukan apapun didalam braket{},  nilai awal bisa diluar while
//inkermen/dekremen diakhir while sebelum ditutup
// do....while jalanin dulu baru cek kondisi/ jika kondisi false akan dijalankan 1 kali
// kalo while tidak akan dijalankan jika kondisi false
// foreach : pengurangan khusus array

// for( $i = 0; $i < 5; $i++ ) {
//     echo "Hello world! <br>";
// }

// $i = 0;
// while( $i < 5 ) {
//     echo "Hello World! <br>";
//     $i++;
// }

// $i = 10;
// do {
//     echo "Hello World! <br>";
// $i++;
// } while( $i < 5 );


?>